### ISSUE TITLE
Not working soueces

### ISSUE THREAD

**Issue by Mrunknow3** [Zenda-Cross/vega-app#84]
Moviemod:- just finding a server and not playing

Autoembed:- movie working series not

Hdhub4u :- movie working and i think series not possible. 

Primewire:- same as moviemod

Ae Anime:- not working

Lux movies:- searching not working

**Comment by Zenda-Cross** [comment]
Moviemod:- it only has one streamable server other only supports downloading, if it's not working that problem is in their server also it's working fine for me

Autoembed- their website is also not working currently

Hdhub4u :- they provide most series only in zip files that's why it is not working 

Primewire:- only one server is supported, use VPN most ISPs have blocked their domain

Ae Anime:- their website is down

Lux movies:- Cloudflare firewall issue, mostly unfixable but I will try what I can do.

**Comment by Mrunknow3** [comment]
Thanks for what works, but you need to add any good hindi anime source like animedekho and toonworld4all.
